/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atelierswing.view;

import atelierswing.entity.Chambre;
import atelierswing.services.ChambreService;
import java.util.List;

/**
 *
 * @author formation
 */
public class JPanelListeChambres extends javax.swing.JPanel {

    /**
     * Creates new form JPaneListeChambres
     */
    public JPanelListeChambres() {
        initComponents();
        
        ChambreService serviceChambre= new ChambreService();
        List<Chambre> listeChambres= serviceChambre.lister();
        TableModelChambre modeleChambre = new TableModelChambre(listeChambres);
        this.jtListeChambres.setModel(modeleChambre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbAjouter = new javax.swing.JButton();
        jbModifier = new javax.swing.JButton();
        jbSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtListeChambres = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jbAjouter.setText("Ajouter");
        jbAjouter.setFocusable(false);
        jbAjouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAjouter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjouterActionPerformed(evt);
            }
        });
        jToolBar1.add(jbAjouter);

        jbModifier.setText("Modifier");
        jbModifier.setFocusable(false);
        jbModifier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbModifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbModifier);

        jbSupprimer.setText("Supprimer");
        jbSupprimer.setFocusable(false);
        jbSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbSupprimer);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jtListeChambres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtListeChambres);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjouterActionPerformed
        // TODO add your handling code here:
        
        JPanelPrincipal panneauPrincipal = (JPanelPrincipal) this.getParent();
        
        panneauPrincipal.RemplaceCompsantCentral(new JpanelChambre());
        
        
    }//GEN-LAST:event_jbAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbAjouter;
    private javax.swing.JButton jbModifier;
    private javax.swing.JButton jbSupprimer;
    private javax.swing.JTable jtListeChambres;
    // End of variables declaration//GEN-END:variables
}
