/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atelierswing.view;

import atelierswing.entity.Hotel;
import atelierswing.services.HotelServices;

/**
 *
 * @author formation
 */
public class JpanelHotelModification extends javax.swing.JPanel {

    /**
     * Creates new form JpanelHotelModification
      */
    private Hotel hotel;
    public JpanelHotelModification() {
        initComponents();
    }
    
    

    JpanelHotelModification(Hotel hotel) {
        this.hotel=hotel;
        initComponents();
        
       this.JTNom.setText(hotel.getNom());
       this.jtNumhotel.setText( Long.toString(hotel.getNumHotel()) );
       this.JTcodePostale.setText(Long.toString( hotel.getCodep()));
      
       
       this.jtlocalite.setText(hotel.getLoaclite());
       this.JTRue.setText(hotel.getRue());
        
 
      // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NOM = new javax.swing.JLabel();
        NUMHOTEL = new javax.swing.JLabel();
        LOCALITE = new javax.swing.JLabel();
        RUE = new javax.swing.JLabel();
        CODEPOSTALE = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JTNom = new javax.swing.JTextField();
        jtNumhotel = new javax.swing.JTextField();
        jtlocalite = new javax.swing.JTextField();
        JTRue = new javax.swing.JTextField();
        JTcodePostale = new javax.swing.JTextField();

        jLabel1.setText("Modification de l'hotel");

        NOM.setText("NOM");

        NUMHOTEL.setText("NUMERO HOTEL");

        LOCALITE.setText("LACLITE");

        RUE.setText("RUE");

        CODEPOSTALE.setText("CODE POSTALE");

        jButton1.setText("Valider");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NUMHOTEL)
                                    .addComponent(NOM)
                                    .addComponent(LOCALITE))
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtlocalite, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(jtNumhotel)
                                    .addComponent(JTNom)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CODEPOSTALE)
                                    .addComponent(RUE))
                                .addGap(137, 137, 137)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTcodePostale)
                                    .addComponent(JTRue)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1)))
                .addGap(56, 56, 56))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NOM)
                    .addComponent(JTNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NUMHOTEL)
                    .addComponent(jtNumhotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LOCALITE)
                    .addComponent(jtlocalite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RUE)
                    .addComponent(JTRue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CODEPOSTALE)
                    .addComponent(JTcodePostale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Hotel hotel = new Hotel();
        
        hotel.setNom(this.JTNom.getText());
        hotel.setNumHotel(Long.valueOf(this.jtNumhotel.getText()));
        hotel.setLoaclite(this.jtlocalite.getText());
        hotel.setRue(this.JTRue.getText());
        hotel.setCodep(Long.valueOf(this.JTcodePostale.getText()));
        
        
        HotelServices  service = new HotelServices();
       
        
        service.modifier(hotel);
      
        
      //  service.SelectHotel(hotel);
        
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.RemplaceCompsantCentral(new JPanelListeHotels());
        
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CODEPOSTALE;
    private javax.swing.JTextField JTNom;
    private javax.swing.JTextField JTRue;
    private javax.swing.JTextField JTcodePostale;
    private javax.swing.JLabel LOCALITE;
    private javax.swing.JLabel NOM;
    private javax.swing.JLabel NUMHOTEL;
    private javax.swing.JLabel RUE;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jtNumhotel;
    private javax.swing.JTextField jtlocalite;
    // End of variables declaration//GEN-END:variables
}
