/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atelierswing.view;

import atelierswing.entity.Hotel;
import atelierswing.services.HotelServices;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.swing.table.TableModel;

/**
 *
 * @author formation
 */
public class JPanelListeHotels extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListeHotels
     */
    public JPanelListeHotels() {
        initComponents();
        
        
        
        //Code maison
        HotelServices service= new HotelServices();
        List<Hotel>  listehotels = service.listerHotel();
        
        TableModelHotel model= new TableModelHotel(listehotels);
        this.jtListeHotels.setModel(model);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbAjouter = new javax.swing.JButton();
        jbModifier = new javax.swing.JButton();
        jbSupprimer = new javax.swing.JButton();
        jspCentre = new javax.swing.JScrollPane();
        jtListeHotels = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jbAjouter.setText("Ajouter");
        jbAjouter.setFocusable(false);
        jbAjouter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAjouter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjouterActionPerformed(evt);
            }
        });
        jToolBar1.add(jbAjouter);

        jbModifier.setText("Modifier");
        jbModifier.setFocusable(false);
        jbModifier.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbModifier.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModifierActionPerformed(evt);
            }
        });
        jToolBar1.add(jbModifier);

        jbSupprimer.setText("Supprimer");
        jbSupprimer.setFocusable(false);
        jbSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSupprimerActionPerformed(evt);
            }
        });
        jToolBar1.add(jbSupprimer);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jtListeHotels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jspCentre.setViewportView(jtListeHotels);

        add(jspCentre, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjouterActionPerformed
        // TODO add your handling code here:
        
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.RemplaceCompsantCentral(new JpanelHotel());
    }//GEN-LAST:event_jbAjouterActionPerformed

    private void jbModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModifierActionPerformed
        // TODO add your handling code here:
        
        
        int indiceSlelectionnee = jtListeHotels.getSelectedRow();
        TableModel model = jtListeHotels.getModel();
        Long id = (Long) model.getValueAt(indiceSlelectionnee, 0);
        
        
        HotelServices service = new HotelServices();
        Hotel hotel= service.SelectHotel(id);
        
   
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.RemplaceCompsantCentral(new JpanelHotelModification(hotel));
       
    }//GEN-LAST:event_jbModifierActionPerformed

    private void jbSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSupprimerActionPerformed
        // TODO add your handling code here:
        
        int ligneSelecionee = jtListeHotels.getSelectedRow();
        TableModel model  = jtListeHotels.getModel();
        Long id= (Long)  model.getValueAt(ligneSelecionee, 0);
        
        HotelServices  service = new HotelServices();
        service.supprimerhotel(id);
        
        JPanelPrincipal  parent = (JPanelPrincipal) this.getParent();
        parent.RemplaceCompsantCentral(new JPanelListeHotels());
        
    }//GEN-LAST:event_jbSupprimerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbAjouter;
    private javax.swing.JButton jbModifier;
    private javax.swing.JButton jbSupprimer;
    private javax.swing.JScrollPane jspCentre;
    private javax.swing.JTable jtListeHotels;
    // End of variables declaration//GEN-END:variables
}
