/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atelierswing.view;

/**
 *
 * @author formation
 */
public class JPanelListeReservations extends javax.swing.JPanel {

    /**
     * Creates new form JPanelListeReservations
     */
    public JPanelListeReservations() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jbAjout = new javax.swing.JButton();
        jbModification = new javax.swing.JButton();
        jbSupprimer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtReservations = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jbAjout.setText("Ajouter");
        jbAjout.setFocusable(false);
        jbAjout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbAjout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAjoutActionPerformed(evt);
            }
        });
        jToolBar1.add(jbAjout);

        jbModification.setText("Modifier");
        jbModification.setFocusable(false);
        jbModification.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbModification.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbModification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificationActionPerformed(evt);
            }
        });
        jToolBar1.add(jbModification);

        jbSupprimer.setText("Supprimer");
        jbSupprimer.setFocusable(false);
        jbSupprimer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbSupprimer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jbSupprimer);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jtReservations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtReservations);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAjoutActionPerformed
        JPanelPrincipal parent = (JPanelPrincipal) this.getParent();
        parent.RemplaceCompsantCentral(new JPanelReservation());

    }//GEN-LAST:event_jbAjoutActionPerformed

    private void jbModificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbModificationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton jbAjout;
    private javax.swing.JButton jbModification;
    private javax.swing.JButton jbSupprimer;
    private javax.swing.JTable jtReservations;
    // End of variables declaration//GEN-END:variables
}